# Generated by Django 3.1.3 on 2020-12-05 16:49

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('DateOfBirth', models.DateField()),
                ('CNIC', models.CharField(max_length=12)),
                ('Address', models.CharField(max_length=100)),
                ('Phone_No', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Account_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('Membership_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Valid_From', models.DateTimeField(default=django.utils.timezone.now)),
                ('Valid_To', models.DateTimeField(verbose_name=datetime.datetime)),
                ('Approved_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.AddField(
            model_name='member',
            name='Member_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.membership'),
        ),
    ]
