# Generated by Django 3.1.3 on 2020-12-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201205_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='CNIC',
            field=models.CharField(max_length=13),
        ),
    ]
