# Generated by Django 3.1.3 on 2020-12-07 11:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201207_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='Valid_To',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 11, 17, 12, 147351, tzinfo=utc)),
        ),
    ]
