# Generated by Django 3.1.3 on 2020-12-06 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201205_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='Employee_Type',
            field=models.CharField(choices=[('PE', 'ParkingEmployee'), ('PA', 'ParkingAdmin')], default='ParkingEmployee', max_length=2),
        ),
        migrations.AddField(
            model_name='member',
            name='Membership_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.membership'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Account_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.accounts'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Account_ID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.accounts'),
        ),
        migrations.AlterField(
            model_name='member',
            name='Member_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
