# Generated by Django 3.1.3 on 2020-12-11 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20201207_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='Membership_ID',
        ),
        migrations.AddField(
            model_name='membership',
            name='Member_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.member'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Approved_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Valid_To',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 16, 24, 25, 535902, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('Bill_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Generated_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Due_Date', models.DateTimeField(default=datetime.datetime(2021, 1, 8, 16, 24, 25, 536732, tzinfo=utc))),
                ('Paid_Status', models.BooleanField(default=False)),
                ('Membership_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.member')),
            ],
        ),
    ]
