# Generated by Django 3.1.3 on 2020-12-11 20:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20201211_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Bill_Amount',
            field=models.CharField(default=1000, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='Due_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 8, 20, 33, 39, 72410, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Valid_To',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 20, 33, 39, 71758, tzinfo=utc)),
        ),
    ]
