# Generated by Django 3.1.3 on 2020-12-21 10:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_auto_20201213_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Due_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 10, 49, 17, 111251, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Approved_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Valid_To',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 10, 49, 17, 109468, tzinfo=utc)),
        ),
    ]
