# Generated by Django 3.1.3 on 2020-12-21 16:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_auto_20201221_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='Bill_Type',
            field=models.CharField(choices=[('MC', 'MemberRegistration'), ('VR', 'VehicleRegistration'), ('PV', 'ParkVehicle'), ('MR', 'MembershipRenewal')], default='MemberRegistration', max_length=2),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Due_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 16, 47, 23, 806691, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Valid_To',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 16, 47, 23, 805999, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('Vehicle_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Vehicle_Model', models.CharField(max_length=50)),
                ('Member_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.member')),
            ],
        ),
    ]
