# Generated by Django 3.1.3 on 2020-12-23 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_auto_20201221_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Due_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 9, 56, 2, 885008, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Valid_To',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 9, 56, 2, 884354, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('Parking_ID', models.AutoField(primary_key=True, serialize=False)),
                ('In_Time', models.DateTimeField(default=datetime.datetime(2020, 12, 23, 9, 56, 2, 886310, tzinfo=utc))),
                ('Out_Time', models.DateTimeField(blank=True)),
                ('Slot', models.CharField(max_length=5)),
                ('Vehicle_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.vehicle')),
            ],
        ),
    ]
