# Generated by Django 3.1.3 on 2020-12-23 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_auto_20201223_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Due_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 9, 59, 53, 527978, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Valid_To',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 9, 59, 53, 527261, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parking',
            name='In_Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 9, 59, 53, 529313, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parking',
            name='Out_Time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
