# Generated by Django 3.1.3 on 2020-12-23 10:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_auto_20201223_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Due_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 10, 23, 52, 858262, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Valid_To',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 10, 23, 52, 857609, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Parking',
        ),
    ]
