# Generated by Django 3.1.3 on 2020-12-23 10:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_auto_20201223_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('Slot_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Occupied_Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='bill',
            name='Due_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 10, 32, 40, 565380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Valid_To',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 23, 10, 32, 40, 564468, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('Parking_ID', models.AutoField(primary_key=True, serialize=False)),
                ('In_Time', models.DateTimeField(default=datetime.datetime(2020, 12, 23, 10, 32, 40, 566937, tzinfo=utc))),
                ('Out_Time', models.DateTimeField(blank=True, null=True)),
                ('Slot_Given', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.slot')),
                ('Vehicle_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.vehicle')),
            ],
        ),
    ]
