# Generated by Django 3.1.3 on 2020-12-24 09:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_auto_20201223_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Due_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 9, 34, 1, 337857, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Valid_To',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 24, 9, 34, 1, 337213, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parking',
            name='In_Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 9, 34, 1, 340225, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Payment_Date', models.DateTimeField(default=datetime.datetime(2020, 12, 24, 9, 34, 1, 338634, tzinfo=utc))),
                ('Payment_Method', models.CharField(choices=[('V', 'Visa'), ('M', 'Mastercard'), ('C', 'Cash')], default='Cash', max_length=2)),
                ('Bill_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.bill')),
                ('Payment_Supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
            ],
        ),
    ]
