# Generated by Django 3.1.3 on 2020-12-26 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_auto_20201224_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='Approved_By',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Approved_By',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.employee'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='Registeration_Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 11, 20, 8, 174859, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Due_Date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 11, 20, 8, 161995, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Valid_To',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 11, 20, 8, 160500, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='parking',
            name='In_Time',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 11, 20, 8, 175880, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Payment_Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 26, 11, 20, 8, 174107, tzinfo=utc)),
        ),
    ]
